### ISSUE TITLE
runtime-configuration

### ISSUE THREAD

**Issue by mansisce** [americanexpress/one-app-ducks#19]
# 🐞 Bug Report

## Describe the bug

On readme file https://github.com/americanexpress/one-app/blob/main/runtime-configuration.md is throwing 404 error

**Comment by nellyk** [comment]
Thank you for raising this.

**Comment by nellyk** [comment]
updating line 280 on the ReadMe to this https://github.com/americanexpress/one-app/blob/main/docs/api/server/Environment-Variables.

**Comment by infoxicator** [comment]
fixed here https://github.com/americanexpress/one-app-ducks/commit/eca8e82adec4404bafb770371eefaf3f5e797a27fi
